baseURL = "https://lianas.org/"
title = "Liana Laboratories"
languageCode = "en-us"

copyright = "Powered by Hugo • © Liana"
enableEmoji = true

[params]
  description = "Personal blog"
  dateFormat = "2006-01-02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[module]
  [[module.imports]]
    path = "github.com/janraasch/hugo-bearblog"

[[menus.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 99
