baseURL = "https://lianas.org/"
title = "Liana S"
theme = "hugo-bearblog"
languageCode = "en-us"

copyright = ""
enableEmoji = true

[params]
  description = "Personal blog"
  dateFormat = "2006-01-02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[module]
  [[module.imports]]
    path = "github.com/janraasch/hugo-bearblog"
